version: '2'
services:
  rs-rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    networks:
      - regards_IT_network

  rs-postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=azertyuiop123456789
      - POSTGRES_USER=azertyuiop123456789
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - regards_IT_network

  rs-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0
    environment:
      - cluster.name=regards
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2500m -Xmx2500m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - regards_IT_network

  rs-build:
    image: 172.26.46.158/rs-maven
    environment:
      - BRANCH_NAME
      - WORKSPACE
      - CI_DIR
      - MODE
      - MAVEN_OPTS=-Xms2500m -Xmx2500m
    volumes:
      - /DATA/maven-multibranch-repository:/localRepository
      - /usr/bin/docker:/bin/docker # link docker - only useful for deploy MODE
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.:/app_to_build
    links:
      - rs-rabbitmq
      - rs-postgres
      - rs-elasticsearch
    networks:
      - regards_IT_network

networks:
  regards_IT_network:
    external:
      name: regards_IT_network
